apiVersion: dataprotection.archinfra.io/v1alpha1
kind: RestoreRequest
metadata:
  name: mysql-prod-restore
  namespace: backup-system
spec:
  sourceRef:
    name: mysql-prod
  # Prefer snapshotRef because it already knows the storage and storage path.
  snapshotRef:
    name: mysql-prod-manual-minio-primary-snapshot
  target:
    mode: InPlace
    driverConfig:
      mysql:
        restoreMode: merge
