apiVersion: dataprotection.archinfra.io/v1alpha1
kind: RestoreJob
metadata:
  name: mysql-prod-restore
  namespace: backup-system
spec:
  sourceRef:
    name: mysql-prod
  snapshotRef:
    name: mysql-prod-manual-nfs-nfs-primary-snapshot
  jobRuntime:
    activeDeadlineSeconds: 1800
  notificationRefs:
    - name: ops-webhook
  reason: restore latest verified snapshot
