apiVersion: v1
kind: Namespace
metadata:
  name: backup-system
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-runtime-auth
  namespace: backup-system
type: Opaque
stringData:
  password: "<MYSQL_ROOT_PASSWORD>"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-runtime-auth
  namespace: backup-system
type: Opaque
stringData:
  password: "<REDIS_PASSWORD>"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: backup-system
type: Opaque
stringData:
  access-key: "<S3_ACCESS_KEY>"
  secret-key: "<S3_SECRET_KEY>"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-source-auth
  namespace: backup-system
type: Opaque
stringData:
  access-key: "<MINIO_SOURCE_ACCESS_KEY>"
  secret-key: "<MINIO_SOURCE_SECRET_KEY>"
