apiVersion: v1
kind: Namespace
metadata:
  name: backup-system
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-runtime-auth
  namespace: backup-system
type: Opaque
stringData:
  password: "<MYSQL_ROOT_PASSWORD>"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: backup-system
type: Opaque
stringData:
  access-key: "<MINIO_ACCESS_KEY>"
  secret-key: "<MINIO_SECRET_KEY>"
