apiVersion: dataprotection.archinfra.io/v1alpha1
kind: BackupPolicy
metadata:
  name: mysql-smoke-minio
  namespace: backup-system
spec:
  sourceRef:
    name: mysql-smoke
  storageRefs:
    - name: minio-primary
  schedule:
    cron: "*/3 * * * *"
    concurrencyPolicy: Forbid
  jobRuntime:
    activeDeadlineSeconds: 1800
  retentionRef:
    name: keep-last-3
  notificationRefs:
    - name: ops-webhook
