apiVersion: dataprotection.archinfra.io/v1alpha1
kind: BackupJob
metadata:
  name: mysql-smoke-manual-nfs
  namespace: backup-system
spec:
  sourceRef:
    name: mysql-smoke
  storageRef:
    name: nfs-primary
  retentionRef:
    name: keep-last-3
  notificationRefs:
    - name: ops-webhook
  reason: manual smoke backup to nfs
