apiVersion: dataprotection.archinfra.io/v1alpha1
kind: RestoreJob
metadata:
  name: mysql-smoke-restore
  namespace: backup-system
spec:
  sourceRef:
    name: mysql-smoke
  snapshotRef:
    name: mysql-smoke-manual-nfs-nfs-primary-snapshot
  jobRuntime:
    activeDeadlineSeconds: 1800
  # importSource:
  #   storageRef:
  #     name: nfs-primary
  #   path: imports/cluster-a/mysql-smoke.tgz
  #   format: auto
  notificationRefs:
    - name: ops-webhook
  reason: restore validated smoke snapshot
