apiVersion: dataprotection.archinfra.io/v1alpha1
kind: BackupPolicy
metadata:
  name: mysql-smoke-fanout
  namespace: backup-system
spec:
  sourceRef:
    name: mysql-smoke
  storageRefs:
    - name: minio-primary
    - name: nfs-primary
  schedule:
    cron: "*/10 * * * *"
    concurrencyPolicy: Forbid
  retentionRef:
    name: keep-last-3
  notificationRefs:
    - name: ops-webhook
  jobRuntime:
    ttlSecondsAfterFinished: 1800
