apiVersion: dataprotection.archinfra.io/v1alpha1
kind: BackupPolicy
metadata:
  name: redis-cluster-every-5m
  namespace: backup-system
spec:
  sourceRef:
    name: redis-cluster
  storageRefs:
    - name: minio-primary
  schedule:
    cron: "*/5 * * * *"
    concurrencyPolicy: Forbid
  retentionPolicyRef:
    name: mysql-daily-retention
  retention:
    keepLast: 3
