apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  namespace: backup-system
type: Opaque
stringData:
  password: replace-me
---
apiVersion: dataprotection.archinfra.io/v1alpha1
kind: BackupSource
metadata:
  name: mysql-prod
  namespace: backup-system
spec:
  addonRef:
    name: mysql-dump
  endpoint:
    host: mysql-0.mysql.app.svc.cluster.local
    port: 3306
    username: root
    passwordFrom:
      name: mysql-auth
      key: password
  parameters:
    database: appdb
