apiVersion: dataprotection.archinfra.io/v1alpha1
kind: RestoreJob
metadata:
  name: mysql-prod-restore
  namespace: backup-system
spec:
  sourceRef:
    name: mysql-prod
  snapshotRef:
    name: replace-with-snapshot-name
  notificationRefs:
    - name: ops-webhook
  reason: restore mysql snapshot
